/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  safelist: [
    'text-순수',
    'text-냉정',
    'text-광기',
    'text-활발',
    'text-우울',
    'text-순수-dark',
    'text-냉정-dark',
    'text-광기-dark',
    'text-활발-dark',
    'text-우울-dark',
    'bg-순수',
    'bg-냉정',
    'bg-광기',
    'bg-활발',
    'bg-우울',
    'border-순수',
    'border-냉정',
    'border-광기',
    'border-활발',
    'border-우울',
    'hover:border-순수',
    'hover:border-냉정',
    'hover:border-광기',
    'hover:border-활발',
    'hover:border-우울',
    'hover:dark:border-순수',
    'hover:dark:border-냉정',
    'hover:dark:border-광기',
    'hover:dark:border-활발',
    'hover:dark:border-우울',
    'border-순수-dark',
    'border-냉정-dark',
    'border-광기-dark',
    'border-활발-dark',
    'border-우울-dark',
    'from-순수',
    'from-냉정',
    'from-광기',
    'from-활발',
    'from-우울',
    'to-순수/80',
    'to-냉정/80',
    'to-광기/80',
    'to-활발/80',
    'to-우울/80',
  ],
  theme: {
    extend: {
      colors: { // color가 아니다. colors로 입력할 것
        '순수': { DEFAULT: '#66c17c', dark: '#4fa163' },
        '냉정': { DEFAULT: '#83b9eb', dark: '#6199cf' },
        '광기': { DEFAULT: '#eb839a', dark: '#cf667d' },
        '활발': { DEFAULT: '#ebdb83', dark: '#cfbe62' },
        '우울': { DEFAULT: '#c683ec', dark: '#a766c9' },
      },
      screens: {
        'mini': '360px',
        'xs': '480px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
      keyframes: {
        slideDown: {
          from: { height: "0px" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        slideUp: {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0px" },
        },
      },
      animation: {
        slideDown: "slideDown 300ms cubic-bezier(0.87, 0, 0.13, 1)",
        slideUp: "slideUp 300ms cubic-bezier(0.87, 0, 0.13, 1)",
      },
    },
  },
  plugins: [],
}